#############################################################################
# Makefile for building: CASE_SWDEP
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  CASE_SWDEP.pro
# Template: subdirs
# Command: C:/Qt/Qt5.3.2/5.3/mingw482_32/bin/qmake.exe -spec win32-g++ CONFIG+=debug -o Makefile CASE_SWDEP.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:/Qt/Qt5.3.2/5.3/mingw482_32/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-MainForm


sub-MainForm-qmake_all:  FORCE
	@test -d MainForm/ || mkdir -p MainForm/
	cd MainForm/ && $(QMAKE) C:/Qt/Project/Fedoseev/CASE_SWDEP/MainForm/MainForm.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd MainForm/ && $(MAKE) -f Makefile qmake_all
sub-MainForm: FORCE
	@test -d MainForm/ || mkdir -p MainForm/
	cd MainForm/ && ( test -e Makefile || $(QMAKE) C:/Qt/Project/Fedoseev/CASE_SWDEP/MainForm/MainForm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-MainForm-make_first: FORCE
	@test -d MainForm/ || mkdir -p MainForm/
	cd MainForm/ && ( test -e Makefile || $(QMAKE) C:/Qt/Project/Fedoseev/CASE_SWDEP/MainForm/MainForm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-MainForm-all: FORCE
	@test -d MainForm/ || mkdir -p MainForm/
	cd MainForm/ && ( test -e Makefile || $(QMAKE) C:/Qt/Project/Fedoseev/CASE_SWDEP/MainForm/MainForm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-MainForm-clean: FORCE
	@test -d MainForm/ || mkdir -p MainForm/
	cd MainForm/ && ( test -e Makefile || $(QMAKE) C:/Qt/Project/Fedoseev/CASE_SWDEP/MainForm/MainForm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-MainForm-distclean: FORCE
	@test -d MainForm/ || mkdir -p MainForm/
	cd MainForm/ && ( test -e Makefile || $(QMAKE) C:/Qt/Project/Fedoseev/CASE_SWDEP/MainForm/MainForm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-MainForm-install_subtargets: FORCE
	@test -d MainForm/ || mkdir -p MainForm/
	cd MainForm/ && ( test -e Makefile || $(QMAKE) C:/Qt/Project/Fedoseev/CASE_SWDEP/MainForm/MainForm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-MainForm-uninstall_subtargets: FORCE
	@test -d MainForm/ || mkdir -p MainForm/
	cd MainForm/ && ( test -e Makefile || $(QMAKE) C:/Qt/Project/Fedoseev/CASE_SWDEP/MainForm/MainForm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: CASE_SWDEP.pro ../../../Qt5.3.2/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf ../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/spec_pre.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/qdevice.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/device_config.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/common/shell-unix.conf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/qconfig.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/qt_functions.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/qt_config.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/spec_post.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/default_pre.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/resolve_config.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/default_post.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/rtti.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/precompile_header.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/warn_on.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/windows.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/testcase_targets.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/exceptions.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/yacc.prf \
		../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/lex.prf \
		CASE_SWDEP.pro
	$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile CASE_SWDEP.pro
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/spec_pre.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/qdevice.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/device_config.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/common/shell-unix.conf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/qconfig.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/qt_functions.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/qt_config.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/spec_post.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/default_pre.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/resolve_config.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/default_post.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/rtti.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/precompile_header.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/warn_on.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/win32/windows.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/testcase_targets.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/exceptions.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/yacc.prf:
../../../Qt5.3.2/5.3/mingw482_32/mkspecs/features/lex.prf:
CASE_SWDEP.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile CASE_SWDEP.pro

qmake_all: sub-MainForm-qmake_all FORCE

make_first: sub-MainForm-make_first FORCE
all: sub-MainForm-all FORCE
clean: sub-MainForm-clean FORCE
distclean: sub-MainForm-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-MainForm-install_subtargets FORCE
uninstall_subtargets: sub-MainForm-uninstall_subtargets FORCE

sub-MainForm-debug:
	@test -d MainForm/ || mkdir -p MainForm/
	cd MainForm/ && ( test -e Makefile || $(QMAKE) C:/Qt/Project/Fedoseev/CASE_SWDEP/MainForm/MainForm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-MainForm-debug

sub-MainForm-release:
	@test -d MainForm/ || mkdir -p MainForm/
	cd MainForm/ && ( test -e Makefile || $(QMAKE) C:/Qt/Project/Fedoseev/CASE_SWDEP/MainForm/MainForm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
release: sub-MainForm-release

sub-MainForm-check:
	@test -d MainForm/ || mkdir -p MainForm/
	cd MainForm/ && ( test -e Makefile || $(QMAKE) C:/Qt/Project/Fedoseev/CASE_SWDEP/MainForm/MainForm.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-MainForm-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

